version: '3.6'

services:
  unifi-mongo:
    image: docker.io/mongo:7
    container_name: unifi-mongo
    volumes:
      - ./volume/mongo/db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
    ports:
      - 27017:27017

  unifi-app:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-app
    network_mode: bridge
    depends_on:
      - unifi-mongo
    volumes:
      - ./volume/app/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      # - MONGO_HOST=unifi-mongo
      - MONGO_HOST=192.168.0.108
      # - MONGO_HOST=192.168.0.111
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      # - MEM_LIMIT=1024
      # - MEM_STARTUP=1024
      # - MONGO_TLS=
      # - MONGO_AUTHSOURCE=
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 7442:7442
      - 7550:7550
      - 7444:7444
      - 6666:6666
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
