# FROM ubuntu:22.04
FROM mongo:4

RUN apt-get update && apt-get install curl wget gnupg -y

# RUN curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
#    gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
#    --dearmor
# RUN echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
# RUN apt-get update
# RUN apt-get install -y mongodb-org

RUN apt-get install binutils openjdk-8-jre-headless -y
RUN echo 'deb [ arch=amd64,arm64 ] https://www.ui.com/downloads/unifi/debian stable ubiquiti' | tee /etc/apt/sources.list.d/100-ubnt-unifi.list
RUN wget -O /etc/apt/trusted.gpg.d/unifi-repo.gpg https://dl.ui.com/unifi/unifi-repo.gpg
RUN apt-get update
RUN apt-get install -y unifi

# CMD ["mongod", "--bind_ip_all"]
ENTRYPOINT ["/usr/lib/unifi/bin/unifi.init", "start"]
